### ISSUE TITLE
Submit s6 RPMs to Fedora

### ISSUE THREAD

**Issue by nisbet-hubbard** [ericwq/ericwq.github.io#1]
Congratulations on getting much of the skaware packaged for Fedora/RHEL earlier this year! Could you please request a formal review so they eventually get into Enterprise Linux?

Becoming a Fedora maintainer is a big commitment to make, but it’d really go a long way towards making s6 a viable competitor to systemd on Red Hat-based distros.

https://docs.fedoraproject.org/en-US/package-maintainers/Package_Review_Process/

**Comment by ericwq** [comment]
sure. please wait for my request.

**Comment by ericwq** [comment]
after discuss this issue with the author of s6, i recommend you to discuss this issue with s6 author. please send a mail to skaware@list.skarnet.org. I am lack of time to finish this work.

**Comment by nisbet-hubbard** [comment]
That's a pity indeed.

I'll keep a lookout for someone who can take on the role of maintaining them for Fedora/RHEL for the long term.
